### GET temperature and local
GET http://localhost:8080/temperature/58046320 HTTP/1.1

### GET temperature and local ERRO 422
GET http://localhost:8080/temperature/5804632 HTTP/1.1

### GET temperature and local ERRO 404
GET http://localhost:8080/temperature/58046321 HTTP/1.1